USE Business



CREATE TABLE salarioFUNCIONARIOS(
FUNCIONARIO_ID INT PRIMARY KEY IDENTITY,
SALARIO SMALLMONEY,
FUNCIONARIO_CPF CHAR(11),
    FOREIGN KEY (FUNCIONARIO_CPF) REFERENCES FUNCIONARIOS(CPF)
)


ALTER TABLE salarioFUNCIONARIOS
ADD dataAdmissao DATE;


SELECT * FROM salarioFUNCIONARIOS

INSERT INTO salarioFUNCIONARIOS(SALARIO,FUNCIONARIO_CPF)values(2489.95,'12345678901')